name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Get dependencies
      run: |
        go mod tidy
        go vet ./...

    - name: Build
      run: go build -v .
